/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as ExpansionRouteImport } from './routes/expansion'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpansionRoute = ExpansionRouteImport.update({
  id: '/expansion',
  path: '/expansion',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/expansion': typeof ExpansionRoute
  '/recommend': typeof RecommendRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/expansion': typeof ExpansionRoute
  '/recommend': typeof RecommendRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/expansion': typeof ExpansionRoute
  '/recommend': typeof RecommendRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cases' | '/expansion' | '/recommend' | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cases' | '/expansion' | '/recommend' | '/tools'
  id: '__root__' | '/' | '/cases' | '/expansion' | '/recommend' | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  ExpansionRoute: typeof ExpansionRoute
  RecommendRoute: typeof RecommendRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expansion': {
      id: '/expansion'
      path: '/expansion'
      fullPath: '/expansion'
      preLoaderRoute: typeof ExpansionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  ExpansionRoute: ExpansionRoute,
  RecommendRoute: RecommendRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
